# Generated by Django 5.0.6 on 2024-05-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AddField(
            model_name="post", name="likes", field=models.IntegerField(default=0),
        ),
    ]
