# Generated by Django 4.2.12 on 2024-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamelevel_guessed_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='guessed_strings',
            field=models.CharField(blank=True, default=' .', max_length=25, null=True),
        ),
    ]
