# Generated by Django 4.2.12 on 2024-05-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_badge_game_gamelevel_hint_word_level_guess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
