# Generated by Django 4.2.12 on 2024-05-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamelevel_guessed_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
