# Generated by Django 5.0.6 on 2024-05-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="like_count", field=models.IntegerField(default=0),
        ),
    ]
