# Generated by Django 5.0.6 on 2024-05-12 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_post_like_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="like_count",),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
