# Generated by Django 4.2.12 on 2024-05-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_level_hint_id_alter_level_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='hint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hint'),
        ),
        migrations.AlterField(
            model_name='level',
            name='word_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
    ]
