# Generated by Django 4.2.12 on 2024-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_level_hint_id_alter_level_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='hint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='word_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
