# Generated by Django 4.2.12 on 2024-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_level_hint_id_alter_level_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lives_left',
            field=models.IntegerField(default=20),
        ),
    ]
