# Generated by Django 4.2.12 on 2024-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_lives_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='guessed_strings',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
