# Generated by Django 4.2.12 on 2024-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamelevel_guessed_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
