# Generated by Django 4.2.12 on 2024-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamelevel_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='guessed_strings',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
