# Generated by Django 4.2.12 on 2024-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_gamelevel_guessed_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
