# Generated by Django 4.2.12 on 2024-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_id_alter_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
