# Generated by Django 4.2.12 on 2024-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='guessed_strings',
            field=models.CharField(default='', max_length=25),
        ),
    ]
