# Generated by Django 4.2.12 on 2024-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gamelevel_guessed_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='total_game_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='level_game_score',
            field=models.IntegerField(default=100),
        ),
    ]
